services:
  db:
    image: postgres:18
    container_name: encourage_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "127.0.0.1:${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql
    restart: unless-stopped

  ds:
    image: vulps23/project-encourage-ds:latest
    container_name: encourage_ds
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  ms:
    image: vulps23/project-encourage-ms:latest
    container_name: encourage_ms
    env_file:
      - .env
    depends_on:
      - ds
    restart: unless-stopped

  bs:
    image: vulps23/project-encourage:latest
    container_name: encourage_bs
    env_file:
      - .env
    ports:
      - "3006:3006"
    depends_on:
      - ds
    restart: unless-stopped

volumes:
  db_data:
