services:
  ds:
    image: vulps23/project-encourage-ds:latest
    container_name: encourage_ds
    ports:
      - "127.0.0.1:${DS_SERVICE_PORT:-3010}:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  ms:
    image: vulps23/project-encourage-ms:latest
    container_name: encourage_ms
    ports:
      - "127.0.0.1:${MS_SERVICE_PORT:-3011}:4001"
    env_file:
      - .env
    depends_on:
      - ds
    restart: unless-stopped

  bs:
    image: vulps23/project-encourage:latest
    container_name: encourage_bs
    env_file:
      - .env
    ports:
      - "${PE_SERVICE_PORT:-3006}:3006"
    depends_on:
      - ds
    restart: unless-stopped

volumes:
  db_data:

networks:
  default:
    ipam:
      config:
        - subnet: 172.22.0.0/16
