CREATE TABLE IF NOT EXISTS `config` (
  `id` int NOT NULL AUTO_INCREMENT,
  `maintenance_mode` tinyint(1) NOT NULL DEFAULT '0',
  `maintenance_reason` longtext,
  `dares_log` varchar(20) DEFAULT NULL,
  `truths_log` varchar(20) DEFAULT NULL,
  `servers_log` varchar(20) DEFAULT NULL,
  `reports_log` varchar(20) DEFAULT NULL,
  `banned_users_log` varchar(20) DEFAULT NULL,
  `errors_log` varchar(20) DEFAULT NULL,
  `advertChannel` varchar(20) NOT NULL,
  `required_votes` int NOT NULL DEFAULT '3',
  `environment` enum('prod','stage','dev') NOT NULL DEFAULT 'dev',
  `client` varchar(20) NOT NULL,
  `secret` varchar(90) NOT NULL,
  `guildId` varchar(20) NOT NULL DEFAULT '1079206786021732412',
  `logs` varchar(20) NOT NULL,
  `top_gg_token` varchar(200) DEFAULT NULL,
  `top_gg_webhook_secret` varchar(90) DEFAULT NULL,
  `announce_password` varchar(90) DEFAULT NULL,
  `bot_invite_url` text NOT NULL,
  `discord_invite_code` varchar(10) NOT NULL,
  `announcementChannelId` varchar(20) DEFAULT NULL,
  `updateChannelId` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='DEPRECATED: Used for database-based config in production. Moving to .env in rewrite.';
