CREATE TABLE IF NOT EXISTS `servers` (
  `id`                   varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,  COMMENT 'Discord server (guild) ID',
  `name`                 text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,         COMMENT 'Discord server name',
  `owner`                varchar(20) NOT NULL,                                                   COMMENT 'Discord user ID of the server owner',
  `hasAccepted`          tinyint(1) NOT NULL DEFAULT '0',                                        COMMENT 'Whether owner has accepted bot terms/rules',
  `isBanned`             tinyint(1) NOT NULL DEFAULT '0',                                        COMMENT 'Whether server is banned from using the bot',
  `banReason`            text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,                  COMMENT 'Reason for server ban',
  `date_created`         datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,                            COMMENT 'When server was first added to database',
  `date_updated`         datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,                            COMMENT 'Last update timestamp',
  `dare_success_xp`      int NOT NULL DEFAULT '50',                                              COMMENT 'XP awarded for successfully completing a dare',
  `dare_fail_xp`         int NOT NULL DEFAULT '25',                                              COMMENT 'XP awarded for failing a dare',
  `truth_success_xp`     int DEFAULT '40',                                                       COMMENT 'XP awarded for successfully completing a truth',
  `truth_fail_xp`        int DEFAULT '40',                                                       COMMENT 'XP awarded for failing a truth',
  `message_xp`           int NOT NULL DEFAULT '0',                                               COMMENT 'XP awarded per message (if enabled)',
  `level_up_channel`     varchar(20) DEFAULT 'UNSET',                                            COMMENT 'Discord channel ID for level-up notifications',
  `announcement_channel` varchar(20) DEFAULT 'UNSET',                                            COMMENT 'Discord channel ID for bot announcements',
  `is_entitled`          tinyint NOT NULL DEFAULT '0',                                           COMMENT 'Whether server has active premium entitlement',
  `entitlement_end_date` datetime DEFAULT NULL,                                                  COMMENT 'When premium entitlement expires',
  `message_id`           varchar(20) DEFAULT NULL,                                               COMMENT 'Discord message ID (purpose unclear)',
  `isDeleted`            tinyint NOT NULL DEFAULT '0',                                           COMMENT 'Whether server has been soft deleted',
  `datetime_deleted`     datetime DEFAULT NULL,                                                  COMMENT 'When server was soft deleted',
  PRIMARY KEY (`id`(18)),
  UNIQUE KEY `id` (`id`),
  KEY `id_idx` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Stores Discord server configuration and settings';
